### ISSUE TITLE
GAP quits

### ISSUE THREAD

**Issue by hungaborhorvath** [gap-packages/profiling#10]
Downloaded 0.3.0, figured out that it needs IO (actually, this is written nowhere, not to the README, not on the webpage, and took me quite some time....), compiled it, then ran the following code: 

````
ghorvath@SamsungLaptop:~$ gap
 ┌───────┐   GAP v4.8.0-210-g0a6dffe of 2015-12-23 18:53:07 (CET)
 │  GAP  │   http://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-gcc-default64
 Libs used:  gmp, readline
 Loading the library and packages ...
 Components: trans 1.0, prim 2.1, small* 1.0, id* 1.0
 Packages:   AClib 1.2, Alnuth 3.0.0, AtlasRep 1.5.0, AutPGrp 1.6, 
             CRISP 1.4.1, Cryst 4.1.12, CrystCat 1.1.6, CTblLib 1.2.2, 
             FactInt 1.5.3, FGA 1.3.0, GAPDoc 1.5.1, IO 4.4.4, IRREDSOL 1.2.4, 
             LAGUNA 3.7.0, Polenta 1.3.2, Polycyclic 2.11, RadiRoot 2.7, 
             ResClasses 3.4.0, Sophus 1.23, SpinSym 1.5, TomLib 1.2.5
 Try '?help' for help. See also  '?copyright' and  '?authors'
gap> G := DihedralGroup(12); 
<pc group of size 12 with 3 generators>
gap> ProfileLineByLine("Dfout.gz"); DirectFactorsOfGroup(G); UnprofileLineByLine();
true
[ Group([ f3, f1 ]), Group([ f2*f3 ]) ]
true
gap> LoadPackage("profiling");
─────────────────────────────────────────────────────────────────────────────
Loading  profiling 0.3.0 (Line by line profiling and code coverage for GAP)
by Christopher Jefferson (http://caj.host.cs.st-andrews.ac.uk/).
Homepage: http://gap-packages.github.io/profiling/
─────────────────────────────────────────────────────────────────────────────
true
gap> OutputAnnotatedCodeCoverageFiles("Dfout.gz", "Dfoutdir");
gap: src/profiling.cc:292: UInt** READ_PROFILE_FROM_STREAM(Bag, Bag, Bag): Assertion `next_stack->parent == current_stack' failed.
Félbeszakítva
````

The last line just says ````Cancelled```` in Hungarian. The file ````Dfout.gz```` exists, I can gunzip it, and get a proper text file. 

What am I doing wrong?

**Comment by ChrisJefferson** [comment]
Exactly which version of GAP and profiling are you using? 4.8.0 beta downloaded and 0.3.0 release?

**Comment by hungaborhorvath** [comment]
GAP development code from github, last commit was ````dac88baa341adb16f2e56d51dbc5d453f63cb313```` (December 20), from profiling I downloaded the tar.bz2 version of 0.3.0.

**Comment by ChrisJefferson** [comment]
Hmm.. seems to work for me (I realise this isn't helpful!) What's your OS? Is it 64-bit or 32-bit?

**Comment by hungaborhorvath** [comment]
64-bit debian jessie. 
I am not sure if it matters, but I have symlinked all packages one by one from the stable gap pkg directory into the development directory, but I recompiled io using the development directory. 

Further, it is actually my working branch, so I have 4 other commits, which I would think are unrelated. However, will try with the master branch.

**Comment by hungaborhorvath** [comment]
Hm, ok, so with the master branch having ````8553b5481fbe2482872c627b0e25aeb7f0948806```` as the latest commit it works....

**Comment by ChrisJefferson** [comment]
Would be interesting to know what commits are messing things up. Of course, the package still shouldn't assert entirely out of GAP! Will look at changing that to at least an `Error`, rather than a C-level assert!

**Comment by hungaborhorvath** [comment]
Hm, of course, I am rather stupid. I am trying to test my new DirectFactorsOfGroup code from the GAP pull request https://github.com/gap-system/gap/pull/379 to make some tst files. Apparently, it has the same problem. My work branch had of course these commits in it, so it must be one of the new code. Can you verify this?

**Comment by ChrisJefferson** [comment]
Can you send e-mail an example `Dfout.gz` which causes a segfault?

**Comment by ChrisJefferson** [comment]
Now fixed in git head.
