### ISSUE TITLE
Print offending filename and line in "malformed profile" error

### ISSUE THREAD

**Issue by zickgraf** [gap-packages/profiling#105]
Currently, the error message displayed for a malformed profile is not very helpful. Including the offending filename and line would simplify debugging. I have hacked this together in https://github.com/zickgraf/profiling/commit/65625647f180a7b7f4d856ef361690c4830126e3 but I don't know how to properly include the C integer in the GAP error message.

**Comment by zickgraf** [comment]
Thanks @ChrisJefferson! :-)

**Comment by ChrisJefferson** [comment]
Sorry it took so long to look at this! I noticed you had some local commits in your profiling, when I went to look at how you implemented this. Do you think some/all of those should be merged in? I didn't look closely at what they did.

**Comment by zickgraf** [comment]
> Sorry it took so long to look at this!

No problem, my manual hack was sufficient for debugging :-)

> I noticed you had some local commits in your profiling, when I went to look at how you implemented this. Do you think some/all of those should be merged in?

I considered these to be local hacks, but some might actually be of interest for everyone. I will create PRs and you can decide.
