### ISSUE TITLE
Flame graph option "chart" does not seem to work as expected

### ISSUE THREAD

**Issue by zickgraf** [gap-packages/profiling#106]
The documentation of `OutputFlameGraph` claims for the option "chart":

> the graph shows the flow of time from left-to-right

Consider the following example:
```
LoadPackage( "profiling" );

func1 := function ( )
    return 1;
end;

func2 := function ( )
    return 1;
end;

func := function ( )
    
    func2( );
    
    func1( );
    
    return 1;
    
end;

LineByLineProfileFunction( func, [ ] );
```

I would expect that in the "chart" output (`flame-chart-standard.svg`) `func2` appears before `func1` but it does not. Even more interesting: If I swap the order in which I define `func1` und `func2`, `func2` really appears before `func1`. Is this a bug or am I misinterpreting the documentation?

**Comment by ChrisJefferson** [comment]
You are correctly interpreting the documentation, someone has at some point broken (or it never worked and I never noticed correctly).
