### ISSUE TITLE
Colouring coverage report

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/profiling#17]
To make the report more visual, it may be nice to colour cells or lines in the table dependently on the coverage %, for example, 0-10% - red, 90-100% green etc.

**Comment by fingolfin** [comment]
See pr #23

**Comment by alex-konovalov** [comment]
Thanks - this feature is now in the picked up version of profiling (see e.g. http://gap-coverage.northeurope.cloudapp.azure.com/coverage-total/)
