### ISSUE TITLE
gmp.h in non-standard location breaks build

### ISSUE THREAD

**Issue by markuspf** [gap-packages/profiling#26]
I have `gmp.h` in `/usr/local/include`, and I built GAP with `configure --with-gmp=/usr/local/`, but

```
# gmake
CXX      src/profiling_la-profiling.lo
In file included from src/gap_cpp_headers/gap_cpp_mapping.hpp:15:0,
                 from src/profiling.cc:5:
src/gap_cpp_headers/include_gap_headers.hpp:4:17: fatal error: gmp.h: No such file or directory
compilation terminated.
*** Error code 1
```

Which is easily solved by using `CXXFLAGS="-I /usr/local/include"` and `LDFLAGS="-L /usr/local/lib"` but still a bit of a nuisance.

**Comment by ChrisJefferson** [comment]
Is this also a problem in other automake based packages? Perhaps I've got an old version of the scripts...

**Comment by fingolfin** [comment]
Is this still reproducible, with the updates to the build system in the master branch?

Also note that including gmp.h is *not* necessary anymore anyway! I'll submit a PR to avoid that.
