### ISSUE TITLE
double free or corruption

### ISSUE THREAD

**Issue by frankluebeck** [gap-packages/profiling#3]
On my Debian wheezy x86_64 system (gcc 4.7.2 (Debian 4.7.2-5))  I can use ProfileLineByLine to produce some profile data. In a new GAP session (Revision 29eadcc) I can load the `profile` package and get the following:

```
gap> LoadPackage("profi");
──────────────────────────────────────────────────────────────
Loading  profiling 0.1 (Line by line profiling and code coverage for GAP)
by Christopher Jefferson (http://caj.host.cs.st-andrews.ac.uk/).
Homepage: http://ChrisJefferson.github.io/profiling/
──────────────────────────────────────────────────────────────
gap> r := ReadLineByLineProfile("/cache/guck2.gz");;
*** glibc detected *** /users/luebeck/gap4/bin/x86_64-unknown-linux-gnu-gcc-default64/gap: double free or corruption (fasttop): 0x00000000014cf380 ***
```
and then GAP hangs.

**Comment by stevelinton** [comment]
I get similar on Centos 6.0  on babbage. I also had to install current versions of autoconf, libtool, texinfo and some other stuff to get it to build.

**Comment by ChrisJefferson** [comment]
This is now (hopefully) fixed. Profiling also (hopefully) works on HPC-GAP (although the profiling package probably won't -- not tried it yet. Loading the profiles into GAP will be fine however).
