### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/profiling#4]
I get the below when I try to compile. What do I have to do to get this to work? I have gmp installed, I'm compiling using clang on a Mac. 

 CXX      src/profiling_la-profiling.lo
In file included from src/profiling.cc:5:
In file included from ./src/gap_cpp_headers/gap_cpp_mapping.hpp:15:
./src/gap_cpp_headers/include_gap_headers.hpp:4:10: fatal error: 'gmp.h' file
      not found
#include <gmp.h>
         ^
1 error generated.
make: *** [src/profiling_la-profiling.lo] Error 1

**Comment by ChrisJefferson** [comment]
Do you build GAP in a normal way, or do you pass "--with-gmp=system" ?

Also, are you putting the package in GAP's "pkg" directory, or trying to build it somewhere else?

**Comment by james-d-mitchell** [comment]
I have gap built with "--with-gmp=no", and I did put the package in the normal "pkg" directory. I managed to work around this by manually copying gmp.h from /usr/local/include/ to profiling/src/. Other than this one wee issue, this is super useful!
