### ISSUE TITLE
Provide a convenience profiling function

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/profiling#42]
I have a function `ProfileFunctionCall` which takes a function, arguments and a folder name and then runs the profiling of that function call. 

This should make it very easy to try out the `profiling` package.

The code looks like this and could be extended by some print statements like "profiling...", "Open the  file/folder (...) in your browser" etc. And it should only remove a folder after asking the user for confirmation.
```
MyProfile := function(f, args, profileDirectoryName)
    local profile, profileFileName;
    profileFileName := Concatenation(profileDirectoryName, ".gz");
    ProfileLineByLine(profileFileName);
    CallFuncList(f, args);
    UnprofileLineByLine();
    profile := ReadLineByLineProfile(profileFileName);
    Exec(Concatenation("rm -r ", profileDirectoryName));
    OutputAnnotatedCodeCoverageFiles(profile, profileDirectoryName);
end;
```

**Comment by ChrisJefferson** [comment]
done, called 'LineByLineProfileFunction'
