### ISSUE TITLE
Add a preview of "most used functions"

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/profiling#45]
Basically list the top 15 functions somewhere on the main html page and make them sorted / sortable by e.g. time spent. Provide links to where this functions where called from, see #44.

**Comment by ChrisJefferson** [comment]
One problem with "most used" is what we mean. We could do most called, or most time spent in that function. I suspect in many cases that will be some tiny function near the bottom, but that still has some value if you can walk back up the functions

**Comment by ssiccha** [comment]
In the case of the parallel gaussian algorithm, Reimer and I had a look in "iprofiler" at what Jendrik wrote. There actually the c functions for multiplying, adding matrices etc used 70% of the CPU time  in the good cases.

We'll have try out a few metrics.

**Comment by ChrisJefferson** [comment]
fixed.
