### ISSUE TITLE
USER_HOME_EXPAND is obsolete, replace by UserHomeExpand

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/profiling#46]
It is used three times in `gap/profiling.gi`. Should be `UserHomeExpand`, see

https://github.com/gap-system/gap/blob/262e53d0513b507ad187278f28557245e8345cd4/lib/obsolete.gd#L582

**Comment by ChrisJefferson** [comment]
USER_HOME_EXPAND still doesn't exist in 4.8, I would prefer to wait until we are sure we are never making another 4.8 release.

**Comment by fingolfin** [comment]
Simple solution, as implemented by digraphs and semigroups: put this into your init.g:
```gap
# load a method for UserHomeExpand if necessary
if not IsBound(UserHomeExpand) then
  BindGlobal("UserHomeExpand", USER_HOME_EXPAND);
fi;
```

**Comment by fingolfin** [comment]
In fact, I made a PR for this a month ago, see #49 , pity it didn't make it into the release.

**Comment by ChrisJefferson** [comment]
fixed
