### ISSUE TITLE
Diffs in tests with GAP 4.9.1 release candidate

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/profiling#47]
There are currently some diffs in the package tests when they are run with the `stable-4.9` branch of the GAP repository. Please see https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging to inspect them: click on the line corresponding to this package and scroll till the very end of the log file to see the output of the package tests, the summary, and further instructions.

As soon as the package tests will run without diffs, they will be moved to https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9. This will be very helpful to monitor in the future that the package is still usable and that no changes in the GAP system break the package.

**Comment by alex-konovalov** [comment]
Now there are no diffs, but still it's not possible to detect whether the tests passed or failed. See for example https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging/jobs/372846610 reported as failing? This is because the script at https://github.com/gap-system/gap-docker-pkg-tests-stable-4.9/blob/master/ci.sh expects the magic line `"#I  No errors detected while testing"` to appear exactly once. Will it be possible to tweak profiling tests in a way to please the script which checks whether tests pass or fail?

**Comment by alex-konovalov** [comment]
This has been resolved - see e.g. https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9/jobs/428438045

**Comment by fingolfin** [comment]
As far as I can tell, the profiling test suite sets a non-zero exit code in case of an error.

I really think that the scripts you quote should be changed to detect that: if there is a non-zero exit code, then there *definitely* was a failure, and there is no need to check for magic lines. Magic lines are only needed if the exit code is zero.

**Comment by alex-konovalov** [comment]
@fingolfin please see an example in https://github.com/gap-system/gap-docker-pkg-tests-master/blob/master/ci.sh and feel free to open an issue there. It runs `make testpackage PKGNAME=$PKG_NAME` (which runs package tests in three settings) and then analyses test logs. That's why exit codes from three runs are thrown away. Perhaps one should actually start with redesigning `make testpackage` target to ensure that it returns a single exit code and fail the whole test if at least one of the three tests failed.
