### ISSUE TITLE
LineByLineProfileFunction sometimes throws an error

### ISSUE THREAD

**Issue by markusbaumeister** [gap-packages/profiling#48]
Sometimes (I have been unable to find out the specifics) the method LineByLineProfileFunction throws the following error:
```
gap> LineByLineProfileFunction( VerifyLibraryStep, [6] );
Error, Unable to open file /tmp/tmVohbeP//prof.gz in
  res := READ_PROFILE_FROM_STREAM( USER_HOME_EXPAND( filename ), 0 ); at /opt/gap4r8/pkg/profiling-1.3.0/gap/profiling.gi:12 called from 
ReadLineByLineProfile( data ) at /opt/gap4r8/pkg/profiling-1.3.0/gap/profiling.gi:337 called from
OutputAnnotatedCodeCoverageFiles( Filename( dir, "/prof.gz" ), Filename( dir, "/output" ) ); at /opt/gap4r8/pkg/profiling-1.3.0/gap/profiling.gi:655 called from
<function "LineByLineProfileFunction">( <arguments> )
 called from read-eval loop at line 2 of *stdin*
```
The arguments are always the same.
The directory /tmp/tmVohbeP/ only contains the subfolder `output`.

**Comment by ChrisJefferson** [comment]
Which operating system are you using? And does it tend to be either very short, or very long, profiles? (or both?)

**Comment by markusbaumeister** [comment]
I am using Debian GNU/Linux 9 (stretch) 64 Bit.
The profile is rather short.

**Comment by ChrisJefferson** [comment]
I've tried to reproduce this, but I haven't been able to. I'll leave it open, in case we can figure out some way of reproducing it, or other people hit it.

**Comment by ChrisJefferson** [comment]
I'm doing a little bit of a clean-up -- if anyone reports this issue in future, I'll look for it again, but lots of stuff was re-written since this issue!
