### ISSUE TITLE
Problem with OutputAnnotatedCodeCoverageFiles

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/profiling#5]
After doing a typical CoverageLineByLine / run tests / UncoverageLineByLine, I get this error when I run OutputAnnotatedCodeCoverageFiles:

```
gap> OutputAnnotatedCodeCoverageFiles(x, filesdir, outdir);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `InputTextFile' on 1 arguments called from
InputTextFile( Filename( DirectoriesPackageLibrary( "profiling", "data" ), 
   "sorttable.js" ) 
 ) on line 244 of file /Users/Wilf/Documents/GAP/pkg/profiling/gap/profiling.\
gi called from
<function "OutputAnnotatedCodeCoverageFiles">( <arguments> )
```

It seems to be failing right at the end of the function - it has already outputted the files except the index, and now tries to make the ```index.html``` page. It fails because ```DirectoriesPackageLibrary( "profiling", "data")``` returns an empty list. If I skip the 5 lines 244-249 then everything is fine except that the table isn't sortable by Javascript.

This is with up-to-date GAP (newest classic GAP commit on Github) and up-to-date profiling package.

**Comment by ChrisJefferson** [comment]
Woops sorry, missing a file. Now committed & pushed
