### ISSUE TITLE
Set <title> tag of the generated html output

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/profiling#53]
It would be nice if a profile could get a name - say the name of the file read by `ReadLineByLineProfile` - which is set as <title> of the generated html files.

At the moment, when I compare different profiles I have to remember which tab is showing which profile.

**Comment by ChrisJefferson** [comment]
Sounds very sensible. It shouldn't be hard (famous last words) to store the filename in the record returned by ReadLineByLineProfile, then put it in the HTML output.

I'm not sure I'll have time in the near future, but I will keep this PR open, and happily accept any patches!

**Comment by ChrisJefferson** [comment]
fixed
