### ISSUE TITLE
Failing tests in GAP master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/profiling#58]
In all three settings for loading other packages, there is the following diff: 
```
########> Diff in /home/gap/inst/gap-master/pkg/profiling-2.0.1/tst/tst4.9/che\
ckmultfiles.tst:31
# Input is:
data[2] = [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ],
               [ 1, 2, 0, 0 ], [ 1, 2, 0, 0 ], [ 1, 1, 0, 0 ], [ 1, 2, 0, 0 ],
               [ 1, 2, 0, 0 ], [ 1, 1, 0, 0 ], [ 1, 2, 0, 0 ], [ 1, 2, 0, 0 ],\
 
               [ 1, 0, 0, 0 ], [ 1, 2, 0, 0 ], [ 1, 3, 0, 0 ], [ 1, 2, 0, 0 ] \
];
# Expected output:
true
# But found:
false
########
```
See e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/453439815

**Comment by fingolfin** [comment]
@alex-konovalov I believe this has been resolved now and can be closed?

**Comment by alex-konovalov** [comment]
Not in the latest release (fails as in https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-staging/jobs/505395559), but fixed in the development version of profiling (https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/504995571). A new release would be nice to have indeed.

**Comment by ChrisJefferson** [comment]
now released
