### ISSUE TITLE
License declaration is missing

### ISSUE THREAD

**Issue by jengelh** [gap-packages/profiling#59]
While the licenses are there for all the third-party sources in the package, a license declaration is absent for the "first-party" source files (e.g. the files matching `*.g`, `*.gd`, `*.gi`). Please add one!

**Comment by jamesjer** [comment]
With my Fedora packager hat on, I will note that the existence of such a file is a necessary prerequisite to this package appearing in any Linux distributions.

**Comment by ChrisJefferson** [comment]
So, that means if I don't put one in, no distributions can mangle my code while badly packaging it?

**Comment by ChrisJefferson** [comment]
sorry, that was probably too sarcastic. However, GAP has in the past often been packaged very badly, the Debian one was, last time I checked, badly broken.

**Comment by jengelh** [comment]
Well, GAP itself has not exactly been a frontrunner in being "fit for packaging" (https://github.com/gap-system/gap/issues/3001 ), so who could blame Debian..

**Comment by ChrisJefferson** [comment]
It's never excusable (in my opinion) to [disable pieces of GAP we consider essential](https://sources.debian.org/patches/gap/4r10p0-7/no-needed-pkg/) , and then [delete error messages which GAP tries to print when it finds vital files missing](https://sources.debian.org/patches/gap/4r10p0-7/remove-infopackage-warning/).

This "GAP" is in a state which no-one tests. I run 224 CPU days of tests on GAP releases.

**Comment by fingolfin** [comment]
Nevertheless, it still would be nice if this package specified a clear license, whether it be GPL 2 or later, BSD, MIT, etc. etc. 

And then perhaps also add a `License` field to `PackageInfo.g`, as we have done with many other packages recently.

**Comment by fingolfin** [comment]
This would also help me selecting MD5 code for addition to the profiling kernel extension, as if I knew its license, then I could pick code that is compatible (I am looking at public domain implementations right now, but I've seen nicer ones under e.g. GPL 2 or later).

That said, this package contains RapidJSON which is MIT license, and FlameGraph which is under the "Common Development and Distribution License" version 1.0. The latter [is *not* GPL compatible](https://www.gnu.org/licenses/license-list.html#CDDL), however, as long as there is no "code linkage" (which there isn't), I believe this does not matter; but other people may disagree and for this reason not want to package this.

**Comment by jamesjer** [comment]
In Fedora land we would not bundle RapidJSON or FlameGraph with this package.  We already have RapidJSON, in fact, so it would be a question of packaging FlameGraph in a suitable way, then packaging profiling so that it uses the separately packaged FlameGraph.  I do not foresee any license trouble with such an arrangement.

Never fear, @ChrisJefferson; I test such arrangements prior to building them for Fedora.

**Comment by ChrisJefferson** [comment]
License is now clarified. I trust any packagers to not significantly break functionality when chopping up code for packaging.
