### ISSUE TITLE
Enhance flame graph with links

### ISSUE THREAD

**Issue by mohamed-barakat** [gap-packages/profiling#82]
It would great if each bar in the flame graph file `flame.svg` located in the directory created by `OutputAnnotatedCodeCoverageFiles` could have links to the corresponding lines of the HTML files located in the same directory.

**Comment by ChrisJefferson** [comment]
Very, very late reply :) I had a look at the flamegraph code I'm using and unfortunately this isn't possible without big internal changes to some perl code i don't understand at all :)
