### ISSUE TITLE
Support output to LCOV format

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/profiling#85]
This would actually simplify coverage submission via GitHub Actions, by allowing us to just use the "Actions" provided by Codecov and Coveralls to upload coverage data -- those prefer respectively (in case of Coveralls) require LCOV files.

**Comment by ChrisJefferson** [comment]
Can anyone find a good guide the LCOV file format? I can only seem to find things about how to use LCOV -- I could try backwards enginnering it, but I was hoping there might be a description somewhere.

**Comment by fingolfin** [comment]
http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php

**Comment by ChrisJefferson** [comment]
profiling, in the master branch, now has `OutputLcovCoverage`. The support isn't complete -- it only does file coverage, not function coverage, but it should be enough to get started.

**Comment by fingolfin** [comment]
Great! This should make it convenient to get `coveralls` integration with GAP packages, not just codecov, when using GitHub Actions: https://github.com/marketplace/actions/coveralls-github-action only accepts lcov files (Codecov is more flexible, but *also* accepts them). It only accepts a single one, but one can use the `lcov` command (in particular `lcov -a` to merge multiple lcov files).

Someone needs to figure out how to combine this with the C/C++ coverage produced by gcov (it should be "standard" as that's what `lcov` was made for, but as always it's easy in theory but in practice may require a lot of fiddling).

Once we know how to do it, we can "simply" adapt https://github.com/gap-system/pkg-ci-scripts/blob/master/gather-coverage.sh to do this. And perhaps also use it in GAP itself.

**Comment by ChrisJefferson** [comment]
I think we should just be able to concatenate the files -- lcov files concatenate cleanly as long as they refer to different source files.

**Comment by fingolfin** [comment]
It seems to work great, as does concatenation, both tested here: https://github.com/oscar-system/GAP.jl/pull/573

It would be great if you could merge PR #86 and then make a fresh release of profiling so that we can start using `OutputLcovCoverage` for GAP and GAP packages. (Well, I guess I could start using it already now by copying its code as in the PR linked above, but a proper release would of course be nicer :-)

**Comment by fingolfin** [comment]
@ChrisJefferson make a new profiling release?
