### ISSUE TITLE
Build failure on cygwin

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/profiling#90]
There is a failure to build `profiling` in GAP's cygwin64 job (see https://github.com/gap-system/gap/pull/4386). This is the error:
```
==== Checking profiling-2.4.1
Running './configure' '/cygdrive/d/a/gap/gap' 
Using settings from /cygdrive/d/a/gap/gap/sysinfo.gap
Running 'gmake' 'clean' 
Makefile.gappkg:41: /cygdrive/d/a/gap/gap/sysinfo.gap: No such file or directory
gmake: *** No rule to make target '/cygdrive/d/a/gap/gap/sysinfo.gap'.  Stop.
Running './configure' '/cygdrive/d/a/gap/gap' 
Using settings from /cygdrive/d/a/gap/gap/sysinfo.gap
Running 'gmake' 
Makefile.gappkg:41: /cygdrive/d/a/gap/gap/sysinfo.gap: No such file or directory
gmake: *** No rule to make target '/cygdrive/d/a/gap/gap/sysinfo.gap'.  Stop.
```
This may be a hint at the "new(ish)" package build system based on `Makefile.gappkg` has issues on Windows / cygwin, but I've never seen reports about that before...

It would be good to fix this, and also at the same time set up CI tests on cygwin for profiling (and other packages as well, I guess)

**Comment by wilfwilson** [comment]
Weird! The package compiles in the CI: https://github.com/gap-packages/profiling/runs/2352647061

So perhaps it's an issue with the particular v2.4.1 released version, rather than the development version (where we run `autogen.sh` first)...

**Comment by wilfwilson** [comment]
The package also compiles in the Windows installer creator https://github.com/ChrisJefferson/sage-windows/actions

**Comment by ChrisJefferson** [comment]
Fixed by https://github.com/gap-actions/setup-cygwin/pull/7
